version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "8998"
      POSTGRES_DB: support_bot
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
      - "8000:8000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    depends_on:
      - db
    network_mode: "service:db"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: unless-stopped
    depends_on:
      - backend
    network_mode: "service:db"

volumes:
  db_data: {}


