services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "8998"
      POSTGRES_DB: support_bot
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BACKEND_PUBLIC_URL=${BACKEND_PUBLIC_URL}
      - BACKEND_URL=http://backend:8080
    env_file:
      - ./.env

volumes:
  db_data: {}


