name: Dev Deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Stop services
      run: |
        # Останавливаем сервисы если они запущены
        pkill -f "python main.py" || true
        pkill -f "python bot.py" || true
        sleep 5
        
    - name: Database migration check
      run: |
        # Проверяем состояние базы данных
        python check_db.py || echo "Database check completed"
        
    - name: Start API service
      run: |
        # Запускаем API в фоне
        nohup python main.py > api.log 2>&1 &
        sleep 10
        
    - name: Health check API
      run: |
        # Проверяем что API запустился
        for i in {1..30}; do
          if curl -f http://localhost:8000/health; then
            echo "API is healthy"
            break
          fi
          echo "Waiting for API... ($i/30)"
          sleep 2
        done
        
    - name: Start Bot service  
      run: |
        # Запускаем бота в фоне
        nohup python bot.py > bot.log 2>&1 &
        sleep 5
        
    - name: Verify deployment
      run: |
        # Проверяем что процессы запущены
        pgrep -f "python main.py" || (echo "API process not found" && exit 1)
        pgrep -f "python bot.py" || (echo "Bot process not found" && exit 1)
        echo "✅ All services are running"
        
    - name: Cleanup old logs
      run: |
        # Оставляем только последние 10 файлов логов
        find . -name "*.log" -type f -mtime +7 -delete || true
        
    - name: Send notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "🚀 Deployment to dev completed successfully"
        else
          echo "❌ Deployment to dev failed"
        fi
